version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/data:/home/osmdata/gpkg
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=mvt_mvp
      - ALLOW_IP_RANGE=0.0.0.0/0