version: '3.4'

services:
  db:
    container_name: postgis
    image: kartoza/postgis
    ports:
      - '5432:5432'
    restart: always
    environment:
      - PGDATA=/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=osmdata
      - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - ./db/data:/data
  dbadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 9000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.org
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
    - ./db/admin:/var/lib/pgadmin
  server:
    container_name: express
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DBNAME=osmdata
  client:
    container_name: next
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - TILE_SERVER_HOST=server
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - db
      - server
