version: '3.4'

services:
  import:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=osmdata
    network_mode: host
    volumes:
      - ./pbf:/home/osmdata/pbf
